import Header from "./components/header";
import Navbar from "./components/navbar";
import './globals.css'
export const metadata = {
  title: "School",
  description: "Generated by Sabbir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto" cz-shortcut-listen="true"
      data-new-gr-c-s-check-loaded="14.1245.0"
      data-gr-ext-installed="">
        <Header/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
