import Header from "./components/header";
import Navbar from "./components/navbar";
import './globals.css'

export const metadata = {
  title: "School",
  description: "Generated by Sabbir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-[1320px] mx-auto px-4  bg-white shadow-2xl text-gray-800 font-sans">
        <Header />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
