import Footer from "@/app/global_components/footer";
import Header from "@/app/User/components/header";
import Navbar from "@/app/User/components/navbar";
import '@/app/globals.css'

export const metadata = {
  title: "School",
  description: "Generated by Sabbir",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-[1350px] mx-auto px-2  bg-white shadow-2xl text-gray-800 font-sans py-2 mb-5">
        <Header />
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
